# NumPy是什么？

NumPy（Numerical Python的缩写）是一个开源的Python科学计算模块，其中包含了许多实用的数学函数，用来处理数值型数据。

为什么要学习NumPy？

1. 很多更高级的扩展模块都依赖于NumPy，比如pandas

2. NumPy中有计算平均数、中位数等数学相关的内置函数，可以在代码中省去很多的循环语句，帮助我们更加快速和科学地进行计算

3. NumPy提供了一个叫做N维数组的数据结构，它和Python中的列表list类似，但前者的输入输出性能远优于后者

NumPy中，最重要和使用最频繁的对象就是N维数组（ndarray）。

要想深入了解NumPy，我们就必须先从它的核心 —— N维数组（ndarray）开始学习。

接下来，我们将分别学习以下几个方面：
1. N维数组的基本概念和常用属性
2. 创建一个N维数组
3. N维数组的运算

# N维数组

N维数组（ndarray）是一个多维数组，描述了相同类型数据的集合。ndarray是N-dimensional array的缩写，也可以叫做数组。

有很多属性可以描述N维数组，最常用的两个属性分别是数据类型和维度。

比如，上一页中，我们用了「整型（int）」和「二维」来描述示例中的数组，依次对应的就是数组的数据类型和维度这两个属性。

接下来，我们将依次学习这两个属性，加深对N维数组的了解。

## 属性一：数据类型

NumPy数组的 数据类型 指的是数组中存储的元素类型，可以是：整型（int）、浮点型（float）、布尔型（bool）等。

需要注意的是，NumPy数组中的所有元素类型必须是一致的。

## 属性二：维度

一维空间相当于一根直线。在这样的空间里，只能前进或者后退，所以只有长度的概念。

二维空间其实就是一个平面。在这个平面上，除了前进、后退以外，还可以向左或者向右，所以有长度和宽度的概念。

三维空间就像是一个立方体。在这个空间里，除了前进、后退、向左和向右移动外，还可以向上或者向下，所以有长度、宽度和高度的概念。

NumPy数组的维度和我们平常说的维度非常相似，接触最多的通常是一维（1D）和二维（2D）数组，可以通过中括号[ ]的层数来确定。

[...]表示一维数组，和Python中的列表长得很像。

在使用print()输出时，它们的区别在于数组之间的元素是用空格分隔，而列表是以逗号分隔。

一维数组的所有元素都在同一「行」里，一行中可以有很多元素。

[[...]]表示二维数组。

二维数组中的每个元素都是一个一维数组，并且每一行的元素数量都是一致的。

在二维数组中：
* 行数代表二维数组中一维数组的数量；
* 列数代表一维数组中元素的数量。

以此类推，[[[...]]]表示三维数组，三维数组中的每个元素都是一个二维数组；[[[[...]]]]表示四维数组，四维数组中的每个元素都是一个三维数组...

由于三维及三维以上的数组多用于复杂的科学计算中，平常很少能接触到，所以在这里我们就不进行系统地学习啦。

# 安装和导入NumPy模块

安装numpy非常简单，在终端中输入代码：`pip install numpy`即可。

如果在自己电脑上安装不上或安装缓慢，可在命令后添加如下配置进行加速：
`pip install numpy -i https://pypi.tuna.tsinghua.edu.cn/simple/`

安装完后，下一步就是导入numpy。

根据NumPy官方文档的倡导，在导入numpy时通常会使用「np」作为numpy的简写，方便以后调用。

导入numpy的具体代码如下：

In [1]:
import numpy as np

# 创建N维数组

在导入numpy后，我们就可以开始创建N维数组啦~

创建N维数组的方式有很多，最简单的一种方式就是调用NumPy模块中的array()函数。

任意序列型对象，也就是列表、元组、数组等数据结构，都可以作为参数传入。

该函数会返回传入的参数所对应的数组。

接下来，通过依次分析如何创建一维数组和二维数组，来更好的理解这个函数吧。

## 创建一维数组

`np.array()`       

这三行代码创建了一个叫做“arr”的一维数组，并输出了该数组。

第一行导入了numpy，并使用"np"作为该模块的简写。

第二行将一个元素全是整型的列表作为参数传入到np.array()中，并将函数返回的结果赋值给了变量arr。

第三行输出了该数组，也就是[1 2 3 4 5]。

In [2]:
import numpy as np
arr =  np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


np.array()是NumPy中用来创建N维数组的函数。

作为参数传入np.array()函数中，该函数将返回一个对应的数组。

任意序列型对象，也就是列表、元组、数组等数据结构，都可以作为参数传入。

## 创建二维数组

掌握了如何创建一维数组后，我们来学习如何创建二维数组。

把「序列中套了一个或多个序列」的数据结构作为参数传入np.array()函数里，会返回一个对应的二维数组。

图中展示了一个列表里套了三个列表的数据结构以及它所生成的二维数组，该二维数组中一共有3个一维数组，其中一维数组中有3个元素：

In [3]:
# TODO 使用import导入numpy，并使用"np"作为该模块的简写
import numpy as np
# TODO 将题目中的序列作为参数传入np.array()函数中，并将生成的二维数组赋值给变量arr
arr = np.array([[1, 2], [4, 5], [7, 9], [11, 12]])
# TODO 使用print()输出变量arr
print(arr)

[[ 1  2]
 [ 4  5]
 [ 7  9]
 [11 12]]


# N维数组的计算

我们将会从3个方向学习N维数组的计算：

1. 数组和数的计算
2. 相同形状数组的计算
3. 不同形状数组的计算

## 1. 数组和数的计算

当数组和数字进行计算的时候，NumPy会将该数字的计算过程应用到数组的所有元素上面。

示例中，在把数组arr和数字2相加时，arr中的每个元素都和2进行了运算：

In [4]:
# 使用import导入numpy，并使用"np"作为该模块的简写
import numpy as np

# 使用np.array()函数创建数组arr
arr = np.array([[2, 1, 7],
                [4, 2, 2]])

# TODO 输出如题所示的运算结果：[[1 0 6]  [3 1 1]]
print(arr - 1)

[[1 0 6]
 [3 1 1]]


## 2. 相同形状数组的计算

当相同形状的数组进行计算时，运算也是在相应的元素上进行。

示例中，arrOne是一个2x3的二维数组，arrTwo也是一个2x3的二维数组。

在计算 arrOne-arrTwo 时，arrOne中每个元素都减去了在arrTwo中相对应位置的元素：

In [5]:
# 使用import导入numpy，并使用"np"作为该模块的简写
import numpy as np

# 使用np.array()函数创建数组arrOne
arrOne = np.array([[5, 0], [0, 5]])
# 使用np.array()函数创建数组arrTwo
arrTwo = np.array([[10, 5], [20, 5]])

# TODO 输出如题所示的运算结果：[[15 5]  [20 10]]
print(arrOne + arrTwo)

[[15  5]
 [20 10]]


## 3. 不同形状数组的计算

当不同形状的数组进行运算时，NumPy可以转换这些形状不同的数组，使它们都具有相同的大小，然后再对它们进行运算。

接下来，我们将通过几个不同的案例来感受一下NumPy数组的魅力。

示例中，arrOne是一个1x3的数组，arrTwo是一个1x1的数组。

arrTwo可以沿着右边扩展来匹配arrOne的形状，然后像之前一样在对应位置上进行运算即可：
[0 1 2] + [5] = [5 6 7]

In [6]:
# 使用import导入numpy，并使用"np"作为该模块的简写
import numpy as np

# 使用np.array()函数创建数组arrOne
arrOne = np.array([2, 3, 4])
# 使用np.array()函数创建数组arrTwo
arrTwo = np.array([5])

# TODO 输出如题所示的运算结果：[10 15 20]
print(arrOne * arrTwo)

[10 15 20]


示例中，arrOne是一个4x1的数组，arrTwo是一个1x1的数组。

arrTwo可以沿着下边扩展来匹配arrOne的形状，然后像之前一样在对应位置上进行运算即可：
[[0] [1] [2] [3]] + [[4]] = [[4] [5] [6] [7]]

In [7]:
# 使用import导入numpy，并使用"np"作为该模块的简写
import numpy as np

# 使用np.array()函数创建数组arrOne
arrOne = np.array([[10], [15], [20], [25]])
# 使用np.array()函数创建数组arrTwo
arrTwo = np.array([5])

# TODO 输出如题所示的运算结果：[[5] [10] [15] [20]]
print(arrOne - arrTwo)

[[ 5]
 [10]
 [15]
 [20]]


但不是所有情况下都能进行运算。

假如要和一个mxn的数组进行运算，那么另一个数组的形状必须是以下几种情况：
1. mxn
2. 1xn
3. mx1
4. 1x1

当无法满足以上情况时，程序将会报「ValueError」的错误。示例中，展示了一种不能进行运算的情况：

In [8]:
# 使用import导入numpy，并使用"np"作为该模块的简写
import numpy as np

# 使用np.array()函数创建一个2x3的数组arrOne
arrOne = np.array([[1, 2, 3],
                   [19, 20, 21]])
# 使用np.array()函数创建一个2x2的数组arrTwo
arrTwo = np.array([[0, 1],
                   [3, 1]])
                    
# 输出 arrOne-arrTwo 的运算结果
print(arrOne-arrTwo)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

# 百题斩题目

## 乔老师批量打分
乔老师是夜曲中学的语文老师。

在学习了《Python办公效率化》后，她利用Python实现了自动化批改试卷，并依次将72名学生试卷中第一题和第二题分数存储到了列表 scoreOne 和 scoreTwo 中。

1. 请分别创建这两个列表对应的一维数组，并赋值给变量 scoreOneArr 和 scoreTwoArr。

2. 该试卷的满分为80分，请使用合适的数组运算将每位同学的成绩转化为百分制。

`比如，某位同学第一大题的分数是16分，第二大题的分数是50分，那么最后他的分数是： (16+50)/80*100=82.5，也就是 (第一大题分数+第二大题分数)/80*100。`

将最后的运算结果存储到变量 sumArr 中，并使用print()输出。

In [9]:
# TODO 使用import导入numpy，并使用"np"作为该模块的简写
import numpy as np

# 第一大题学生分数
scoreOne = [16, 16, 18, 16, 20, 18, 14, 16, 8, 18, 14, 18, 20, 10, 16, 20, 16, 18, 20, 16, 20, 20, 18, 18, 16, 14, 16, 10, 12, 16, 10, 16, 16, 18, 20, 16, 20, 18, 18, 18, 14, 16, 20, 20, 18, 6, 20, 18, 20, 12, 20, 12, 20, 14, 14, 18, 18, 12, 18, 16, 20, 20, 18, 20, 20, 16, 18, 18, 14, 12, 16, 16]
# 第二大题学生分数
scoreTwo = [50, 45, 45, 45, 50, 40, 30, 50, 20, 25, 35, 40, 50, 25, 40, 50, 35, 45, 50, 40, 50, 50, 45, 35, 35, 45, 45, 25, 40, 35, 40, 45, 40, 40, 50, 40, 50, 45, 50, 35, 40, 50, 50, 50, 40, 25, 50, 25, 50, 25, 50, 35, 30, 30, 45, 50, 30, 40, 45, 40, 50, 50, 30, 50, 45, 40, 45, 45, 45, 35, 45, 40]

# TODO 使用np.array()函数创建scoreOne对应的一维数组，并赋值给变量scoreOneArr
scoreOneArr = np.array(scoreOne)
# TODO 使用np.array()函数创建scoreTwo对应的一维数组，并赋值给变量scoreTwoArr
scoreTwoArr = np.array(scoreTwo)

# TODO 按照题目要求，使用合适的数组运算计算出每位同学的分数
# 将运算结果赋值给变量sumArr
sumArr = (scoreOneArr + scoreTwoArr) / 80 * 100
# TODO 使用print()输出变量sumArr
print(sumArr)

[82.5  76.25 78.75 76.25 87.5  72.5  55.   82.5  35.   53.75 61.25 72.5
 87.5  43.75 70.   87.5  63.75 78.75 87.5  70.   87.5  87.5  78.75 66.25
 63.75 73.75 76.25 43.75 65.   63.75 62.5  76.25 70.   72.5  87.5  70.
 87.5  78.75 85.   66.25 67.5  82.5  87.5  87.5  72.5  38.75 87.5  53.75
 87.5  46.25 87.5  58.75 62.5  55.   73.75 85.   60.   65.   78.75 70.
 87.5  87.5  60.   87.5  81.25 70.   78.75 78.75 73.75 58.75 76.25 70.  ]


## 客户分析
涛涛是一名高风险高收益的理财产品销售专员。
现在，他需要对一组客户数据进行分析，计算出21岁-25岁（包含21岁和25岁）年龄段客户的平均年龄、平均年收入、年龄中位数、年收入中位数以及预期投入额。

请利用今日所学内容，根据图中的数据依次创建年龄和年收入对应的数组，并计算出 21岁-25岁（包含21岁和25岁）年龄段客户的 平均年龄 、 平均年收入 、 年龄中位数、 年收入中位数 以及 预期投入额，并在最后使用print()格式化输出客户信息。

预期投入额公式为：
预期投入额 =（年龄中位数+年收入中位数）* 购买力。其中，购买力=0.12。

输出示例为：
目标客户为21岁-25岁年龄段客户，平均年龄为xx岁，平均年收入为xxK，年龄中位数为xx岁，年收入中位数为xxK，预期投入额为xxK

本题中需要用到 计算数组的平均数和中位数 这两个知识点，请先点击提示进行学习。

```
计算数组的平均数
可以直接对一个数组对象使用mean()函数，来计算数组中数值的平均数。

例如，创建一个数组age，并计算该数组内所有元素的平均数的代码为：
age = np.array([22,26,21])
ageAvg = age.mean()
print(ageAvg)
最后代码的输出为：
23


计算数组的中位数
由于Python中没有计算中位数的内置函数，所以在计算数组中位数时，需要使用NumPy模块中的np.median()函数。

将数组作为参数传入np.median()函数中即可。

例如，创建一个数组age，并计算该数组的中位数的代码为：
age = np.array([22,26,21])
ageMed = np.median(age)
print(ageMed)
最后代码的输出为：
22
```

In [12]:
# TODO 导入numpy
import numpy as np

# TODO 依次创建年龄和年收入对应的数组
ageArr = np.array([23, 21, 22, 25, 24])
revArr = np.array([154, 114, 145, 132, 198])

# TODO 依次计算年龄的平均值和年收入的平均值
ageAvg = ageArr.mean()
revAvg = revArr.mean()

# TODO 依次计算年龄的中位数和年收入的中位数
ageMed = np.median(ageArr)
revMed = np.median(revArr)

# TODO 根据公式，计算预期投入额
result = (ageMed + revMed) * 0.12

# TODO 根据题目要求，格式化输出结果
print(f"目标客户为21岁-25岁年龄段客户，平均年龄为{ageAvg}岁，平均年收入为{revAvg}K，年龄中位数为{ageMed}岁，年收入中位数为{revMed}K，预期投入额为{result}K")

目标客户为21岁-25岁年龄段客户，平均年龄为23.0岁，平均年收入为148.6K，年龄中位数为23.0岁，年收入中位数为145.0K，预期投入额为20.16K
